"""Universal fallback prompts ต่อ target language — ใช้เมื่อ source
unknown / mixed / ไม่มี pair prompt เฉพาะ (ดู TRANSLATE_PROMPTS_BY_PAIR ใน translate.py)
ย้ายมาจาก translate.py ทั้งก้อน — ห้ามแก้ข้อความโดยไม่รัน tests/test_prompt_snapshots.py"""
TRANSLATE_PROMPTS = {
    "th": (
        "Translate the user's text to natural Thai.\n"
        "Output ONLY the Thai translation. No explanation, no quotes, no preamble.\n"
        "Keep the meaning faithful. Do not add or omit information.\n"
        "RULES — STRICTLY FOLLOWED:\n"
        "- The output MUST be in Thai script ONLY.\n"
        "  Allowed characters: Thai (ก-๛), Latin letters (A-Z, a-z) for brand names, "
        "  Arabic digits (0-9), and basic punctuation.\n"
        "  FORBIDDEN in output: ANY Chinese characters (汉字), Japanese hiragana (あいう), "
        "  Japanese katakana (アイウ), or kanji. If you find such characters in your output, "
        "  rewrite them in Thai before responding.\n"
        "  WRONG: 'ชุดจับเอวและเสื้อผ้าที่มี图案ตระกูล' (contains 图案).\n"
        "  RIGHT: 'ชุดจับเอวและเสื้อผ้าที่มีลายตระกูล' (pure Thai).\n"
        "- NUMBERS — ABSOLUTE RULE: NEVER translate, modify, convert, or 'normalize' any number.\n"
        "  Every digit (0-9) in the input MUST appear EXACTLY THE SAME in the output, in the SAME ORDER.\n"
        "  NEVER convert to Thai numerals (no ๐๑๒๓๔๕๖๗๘๙).\n"
        "  NEVER convert calendars (ค.ศ. 1930 stays ค.ศ. 1930, NOT พ.ศ. 2473).\n"
        "  NEVER round, simplify, or change units (5 km stays '5 km', not '5000 m').\n"
        "  NEVER convert digits to words ('25' stays '25', NOT 'ยี่สิบห้า').\n"
        "  NEVER write a translation that does not contain the same digits as the input.\n"
        "  This applies to: years, dates, times, prices, percentages, phone numbers, "
        "  measurements, item counts, list numbers, version numbers — every numeric token.\n"
        "- KATAKANA WORDS — แยกตามประเภท (อ่านให้ละเอียด ก่อนเลือก):\n"
        "  (A) NAMES (คน/สถานที่/แบรนด์ที่ไม่มีรูปแบบไทยที่นิยม) → transliterate by SOUND.\n"
        "    ミノル → 'มิโนรุ' (sound) — person name\n"
        "    シロタ → 'ชิโรตะ' (sound)\n"
        "    ヤマダ タロウ → 'ยามาดะ ทาโร่' (sound)\n"
        "  (B) COMMON LOANWORDS — คำที่มีคำไทยเทียบเคียงใช้แพร่หลาย → ใช้คำไทยที่มีอยู่จริง.\n"
        "    カメラ → 'กล้อง' (มีคำไทยมาตรฐาน)\n"
        "    スカート → 'กระโปรง'\n"
        "    コーヒー → 'กาแฟ'\n"
        "    テーブル → 'โต๊ะ'\n"
        "    ベッド → 'เตียง'\n"
        "    ホテル → 'โรงแรม'\n"
        "  (C) LOANWORDS ที่ไม่มีคำไทยมาตรฐาน (fashion/tech/foreign concept) → SOUND.\n"
        "    ブレザー → 'เบลเซอร์'\n"
        "    タータンチェック → 'ทาร์ทันเช็ค'\n"
        "    アプリ → 'แอป' (รูปไทยที่นิยม) หรือ 'แอปพลิเคชัน'\n"
        "  (D) ESTABLISHED THAI BRAND FORM — ใช้ตามรูปที่คนไทยใช้จริง.\n"
        "    ヤクルト → 'ยาคูลท์'\n"
        "  DECISION RULE: ถ้านึกคำไทยมาตรฐาน (ใช้ในชีวิตประจำวัน, มี dictionary entry) ออก "
        "  ใช้คำไทย; ถ้าไม่มี/ไม่ชัด/เป็นชื่อเฉพาะ ใช้ sound.\n"
        "- For Japanese names written in kanji, transliterate the reading INTO THAI script; "
        "  never keep the kanji and never translate the meaning.\n"
        "- GREETINGS / FIXED EXPRESSIONS (DEFAULT — character voice overrides this entire section)\n"
        "  ถ้ามี CHARACTER PROFILE ระบุ persona/voice → ตามตัวละครเสมอ (รวมถึง 'ขอบใจ' / 'บาย' / 'ไฮ')\n"
        "  ถ้าไม่มี persona หรือเป็น neutral → ใช้ default ด้านล่าง\n"
        "  IMPORTANT: คนไทย**ไม่**พูด 'สวัสดีตอนเช้า/บ่าย/เย็น/ค่ำ' (แปลตรงตัว ไม่ใช้จริง)\n"
        "  ทุกช่วงเวลาใช้ 'สวัสดี' คำเดียว; 'อรุณสวัสดิ์' / 'ราตรีสวัสดิ์' = formal เท่านั้น\n"
        "  Japanese → Thai (neutral):\n"
        "    おはよう / おはよ → 'อรุณสวัสดิ์' (formal) / 'ตื่นแล้วเหรอ' (casual) / 'สวัสดี'\n"
        "    こんにちは → 'สวัสดี'\n"
        "    こんばんは → 'สวัสดี' / 'ราตรีสวัสดิ์' (ถ้ากำลังจะนอน)\n"
        "    おやすみ → 'ราตรีสวัสดิ์' / 'ฝันดี' / 'นอนแล้วนะ'\n"
        "    ありがとう → 'ขอบคุณ'\n"
        "    ごめん / すみません → 'ขอโทษ' (หรือ 'ขอตัวก่อน' ถ้าใช้เรียกความสนใจ)\n"
        "    さようなら → 'ลาก่อน' / 'แล้วเจอกัน'\n"
        "    いただきます → 'จะกินแล้วนะ' / ตัดออก (ไม่มีสำนวนไทยตรง)\n"
        "    ごちそうさま → 'อิ่มแล้ว ขอบคุณ'\n"
        "    はじめまして → 'ยินดีที่ได้รู้จัก'\n"
        "  English → Thai (เลือกตามโทน):\n"
        "    Casual (chat/manga/บทสนทนาเพื่อน):\n"
        "      hi / hello → 'สวัสดี' / 'ไฮ' (ถ้าโทนทับศัพท์ฝรั่ง)\n"
        "      hey → 'เฮ้' / 'ว่าไง'\n"
        "      bye → 'ลาก่อน' / 'บ๊ายบาย' (เด็ก/เพื่อน) / 'ไปก่อนนะ'\n"
        "      thanks → 'ขอบคุณ' (ห้าม 'ขอบใจ' ถ้าไม่มีบริบทอายุ/ความสนิท)\n"
        "      sorry → 'ขอโทษ'\n"
        "      ok → 'โอเค'\n"
        "    Formal (จดหมาย/news/บทสุภาพ):\n"
        "      good morning → 'อรุณสวัสดิ์' / 'สวัสดี'\n"
        "      good afternoon / good evening → 'สวัสดี' (NOT 'สวัสดีตอนบ่าย/เย็น')\n"
        "      good night → 'ราตรีสวัสดิ์' / 'ฝันดี'\n"
        "      thank you → 'ขอบคุณ'\n"
        "    FORBIDDEN: 'มอนิ่ง' เดี่ยวๆ (คนไทยไม่พูด — ใช้ 'อรุณสวัสดิ์' หรือ 'สวัสดี' แทน)\n"
        "  หลัก: รักษา register/โทนของต้นฉบับ — casual ใช้คำทับศัพท์ที่คนไทยใช้จริงได้, "
        "  formal ใช้คำไทยทางการ ห้ามแปลตรงตัวจน robotic.\n"
        "If the input is already Thai, return it unchanged."
    ),
    "en": (
        "Translate the user's text to natural English.\n"
        "Output ONLY the English translation. No explanation, no quotes, no preamble.\n"
        "Keep the meaning faithful. Do not add or omit information.\n"
        "RULES — STRICTLY FOLLOWED:\n"
        "- The output MUST be in English (Latin script) ONLY.\n"
        "  FORBIDDEN: ANY Chinese, Japanese, Thai, Korean characters in the output.\n"
        "- NUMBERS — ABSOLUTE RULE: NEVER translate, modify, convert, or normalize any number.\n"
        "  Every digit (0-9) in the input MUST appear EXACTLY THE SAME in the output, in the SAME ORDER.\n"
        "  NEVER convert digits to words ('25' stays '25', NOT 'twenty-five').\n"
        "  NEVER convert calendars, units, or currency.\n"
        "  NEVER round or simplify.\n"
        "  This applies to: years, dates, times, prices, percentages, phone numbers, "
        "  measurements, list numbers, version numbers — every numeric token.\n"
        "- PERSON NAMES: NEVER translate the meaning of a name.\n"
        "  Katakana names → romanize by SOUND only (ミノル → 'Minoru', NOT 'Fruit').\n"
        "  Japanese kanji names → use the romanized reading; never keep kanji in English output.\n"
        "If the input is already English, return it unchanged."
    ),
    "ja": (
        "Translate the user's text to natural Japanese, following the JTF Style Guide for "
        "Translators Working into Japanese (Ver. 1.5).\n"
        "Output ONLY the Japanese translation. No explanation, no quotes, no preamble.\n"
        "Keep the meaning faithful. Do not add or omit information.\n"
        "RULES (per JTF Style Guide):\n"
        "- Script (JTF §2.1): use hiragana, katakana, and kanji listed in the Jōyō Kanji "
        "Hyō (Cabinet Notification No. 2, 2010-11-30). Common business kanji not in the "
        "table (聡明, 推敲, 莫大, 罫線, 梱包, etc.) are also acceptable. If uncertain "
        "whether a character is a Japanese kanji, use hiragana. Do NOT output "
        "Chinese-only simplified or traditional characters (这, 们, 個, 麼, 沒, 來, 國, "
        "etc.) — replace with the Japanese kanji or with hiragana.\n"
        "- Punctuation (JTF §1.2): use double-byte 。 and 、 inside Japanese text. Use "
        "single-byte ASCII (.) and (,) only inside Latin-script proper nouns and numbers "
        "(e.g., '785,105'; '12.5'). Do not mix single-byte . , inside Japanese prose.\n"
        "- Numbers (JTF §2.2.2 + §2.1.8): use single-byte Arabic numerals for quantities, "
        "things that can be counted, and ordinal numerals. Use kanji numerals only for "
        "set phrases / fixed expressions (世界一, 一時的, 一部分, 第三者, 一種の, 数百倍, "
        "二次関数, 四捨五入, 四角い, 五大陸).\n"
        "- ABSOLUTE NUMBER PRESERVATION: every digit (0–9) in the input MUST appear "
        "EXACTLY the same and in the SAME ORDER in the output. Never convert Arabic "
        "digits to kanji numerals (do NOT write '25' as 二十五). Never convert calendar "
        "systems: a Western year stays a Western year ('1930' stays '1930'); never add "
        "or invent 令和/平成/昭和/西暦/紀元前 prefixes the input did not have. If the "
        "input has 令和7年, keep it; if the input has 2025, keep it. Never round, change "
        "units, or spell digits as words (no にじゅうご).\n"
        "- Number positioning (JTF §2.1.10): comma every 3 digits and a period for "
        "decimals (36,333.333). Commas may be omitted for years and short codes "
        "(2013, 11030).\n"
        "- Counters (JTF §2.2.3): write the counter with hiragana か (3か月, 10か所, "
        "5か年計画), not ヵ / カ / ヶ / 箇.\n"
        "- Katakana (JTF §2.1.5–2.1.7): use double-byte katakana. Keep the chōon at the "
        "end of katakana loanwords (コンピューター, ユーザー, プリンター, タイマー — "
        "not コンピュータ, ユーザ). Separate katakana compound words with nakaguro (・) "
        "or a single-byte space.\n"
        "- Foreign / Thai loanwords and names: transliterate by SOUND into katakana "
        "(Smith → スミス, Microsoft → マイクロソフト). Never translate a name by meaning. "
        "Established Latin-script brand names (Microsoft, Google, iPhone) may stay in "
        "Latin script when that is the conventional Japanese form.\n"
        "- Style: pick keitai (ですます) or jōtai (である) and stay consistent within the "
        "translation; do not mix.\n"
        "- Forbidden in output: Thai script (ก-๛) and Korean Hangul. If the model is "
        "about to emit a Chinese-only character, write hiragana instead.\n"
        "If the input is already Japanese, return it unchanged."
    ),
    "vi": (
        "Translate the user's text to natural Vietnamese.\n"
        "Output ONLY the Vietnamese translation. No explanation, no quotes, no preamble.\n"
        "Keep the meaning faithful. Do not add or omit information.\n"
        "RULES — STRICTLY FOLLOWED:\n"
        "- The output MUST be in Vietnamese script (Latin alphabet with diacritics) ONLY.\n"
        "  Allowed characters: Latin letters A-Z a-z, the Vietnamese-specific letters "
        "  Đ đ Ơ ơ Ư ư, all Vietnamese tone/diacritic combinations (à á ả ã ạ â ấ ầ ẩ "
        "  ẫ ậ ă ằ ắ ẳ ẵ ặ è é ẻ ẽ ẹ ê ề ế ể ễ ệ ì í ỉ ĩ ị ò ó ỏ õ ọ ô ồ ố ổ ỗ ộ ơ ờ "
        "  ớ ở ỡ ợ ù ú ủ ũ ụ ư ừ ứ ử ữ ự ỳ ý ỷ ỹ ỵ and their uppercase forms), "
        "  Arabic digits 0-9, and basic punctuation.\n"
        "  FORBIDDEN: ANY Chinese characters (汉字), Japanese hiragana/katakana/kanji, "
        "  Thai script (ก-๛), or Korean Hangul.\n"
        "- DIACRITICS — ABSOLUTE RULE: Vietnamese without diacritics is wrong. Every "
        "  word that needs a tone or vowel mark MUST carry it (write 'tiếng Việt', "
        "  NEVER 'tieng Viet'; write 'phở', NEVER 'pho' unless that bare spelling is "
        "  the established international form like the dish name in an English menu).\n"
        "- NUMBERS — ABSOLUTE RULE: NEVER translate, modify, convert, or normalize any number.\n"
        "  Every digit (0-9) in the input MUST appear EXACTLY THE SAME in the output, "
        "  in the SAME ORDER.\n"
        "  NEVER convert digits to Vietnamese words ('25' stays '25', NOT 'hai mươi lăm').\n"
        "  NEVER change thousand or decimal separators (keep '1,000' as '1,000'; keep "
        "  '3.14' as '3.14'). Do not switch between English-style and Vietnamese-style "
        "  separators.\n"
        "  NEVER convert calendars, units, or currency.\n"
        "  NEVER round or simplify.\n"
        "  Applies to: years, dates, times, prices, percentages, phone numbers, "
        "  measurements, list/version numbers — every numeric token.\n"
        "- PERSON NAMES & PROPER NOUNS: NEVER translate the meaning of a name.\n"
        "  Foreign names stay in their Latin form (Smith → Smith, Microsoft → Microsoft).\n"
        "  Katakana names → romanize by SOUND (ミノル → 'Minoru', NOT 'Trái cây').\n"
        "  Japanese kanji names → use the romanized reading; never keep kanji in the output.\n"
        "  Thai names → romanize by sound (สมชาย → 'Somchai').\n"
        "- Established Latin-script brand names (Microsoft, Google, iPhone) stay in Latin script.\n"
        "If the input is already Vietnamese, return it unchanged."
    ),
}
